fty-nutconfig : ensure no delay for moving ups.conf

diff --git a/fty-nutconfig b/fty-nutconfig
--- a/fty-nutconfig
+++ b/fty-nutconfig
@@ -77,7 +77,9 @@ RES=$?
 fi
 
 if [ "$RES" = 0 ] ; then
-    mv "${TMPFILE}" "$NUTCONFIG"
+    # This can take a while and needs space; have our moves atomic
+    mv -f "${TMPFILE}" "${NUTCONFIG}.tmp" || die "Error moving ups.conf from temporary to final directory"
+    mv -f "${NUTCONFIG}.tmp" "${NUTCONFIG}" || die "Error atomically moving ups.conf from temporary to final file"
     chmod 0640 "${NUTCONFIG}"
     chown root:nut "${NUTCONFIG}"
     exit 0
